2018-10-23 00:34:25,498 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/routes.py", line 54, in reset_password_request
    send_password_reset_email(user)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/email.py", line 11, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/templates/email/reset_password.html", line 9, in top-level template code
    <p>{{ url_for('reset_password', token=token, _external=True) }}</p>
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2018-10-23 00:35:17,971 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/__init__.py:69]
2018-10-23 00:35:28,007 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/routes.py", line 54, in reset_password_request
    send_password_reset_email(user)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/email.py", line 11, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/email.py", line 8, in send_email
    msg = Message(subject, sender=sender, recipients=recipients)
NameError: name 'Message' is not defined
2018-10-23 00:37:50,897 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/__init__.py:69]
2018-10-23 00:38:21,967 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/routes.py", line 54, in reset_password_request
    send_password_reset_email(user)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/auth/email.py", line 11, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token)
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/email.py", line 15, in send_email
    Thread(target=send_async_email, args=(current_app.get_current_object(), msg)).start()
  File "/Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/venv/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'get_current_object'
2018-10-23 00:42:08,538 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/mega_tutorial/microblog/app/__init__.py:69]
2018-10-24 15:49:27,075 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/fantasy_football/megascore/app/__init__.py:69]
2018-10-24 15:59:18,009 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/fantasy_football/megascore/app/__init__.py:69]
2018-10-24 16:35:13,275 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/fantasy_football/megascore/app/__init__.py:69]
2018-10-29 16:29:39,716 INFO: Microblog startup [in /Users/falkvandermeirsch/Documents/Python/fantasy_football/megascore/app/__init__.py:69]
